output:
  file: README.md
  mode: replace
formatter: "markdown table"
content: |-
  # AWS Networking Template

  This module provisions essential network components of AWS.

  The resulting resources include
  - A VPC
  - Public subnets (arbitrary numbers)
  - Private subnets (arbitrary numbers)
  - Route tables
  - An internet gateway, if needed
  - A NAT gateway and the associated Elastic IP, if needed
  - Security groups

  ## Usage Example

  ```terraform
  # in `main.tf`
  module "network" {
    source = "github.com/uniglot/aws-networking-template"

    project_name = "module-test"
    vpc_cidr = "10.0.1.0/24"
    pub_sub_cidrs = ["10.0.1.0/25"]
    pri_sub_cidrs = ["10.0.1.128/25"]
    ssh_allowed_cidrs = ["123.123.12.3/32"]
  }
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
